"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['app.py']
DATA_FILES = ['./assets/bearpic.jpg']
OPTIONS = {
    'argv_emulation': True,
    'iconfile': './assets/logo.icns',
    'plist': {'PyRuntimeLocations': ['/opt/anaconda3/bin/python3.7']}
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
